    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cai dat XcodeGen
      run: brew install xcodegen

    - name: Tao Xcode Project
      run: xcodegen generate

    - name: Build Ung dung
      run: |
        xcodebuild -project muyynguyen.xcodeproj \
          -scheme muyynguyen \
          -sdk iphoneos \
          -configuration Release \
          -derivedDataPath ./build \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          build
